### PR TITLE
fix: fix bug in entriesReversed, optimize nextLowerPair

### PR DESCRIPTION
**Pull request by taylorsw04**
This PR broadens testing for nextLowerPair and nextHigherPair, including a regression test for an out-of-bounds bug in entriesReversed.

It also adds an optimized path for nextLowerPair.

### CODE REVIEW

**Comment by qwertie** [comment]
`getOrNextLower` should be named `getPairOrNextLower`. Normally I'd add a corresponding `getPairOrNextHigher`, but I'll accept the PR without it.

Did you detect a performance problem with `nextLowerPair`? I see that `entriesReversed(...).next()` needs a couple of memory allocations (including an implicit allocation for a lambda closure), but the new version also allocates an array of two, which could be avoided with another `reusedArray` parameter.

The readme lists the minified package size ("18K minified"), which was a badge of honor though it has been creeping up. Please update it if we've reached 19/20K.

**Comment by qwertie** [comment]
Hi @taylorsw04, I noticed that there is no public `getPairOrNextHigher` method even though it exists in the nodes. So I added `getPairOrNextHigher`, and fixed some TS compiler errors visible in my VS Code, made some other small tweaks and added an expanded set of tests for `getPairOrNextLower`, `getPairOrNextHigher`, `nextLowerPair` and `nextHigherPair`.

These tests failed for `nextLowerPair` and `getPairOrNextLower` for large trees (but not small trees). I will investigate prior to release, probably today.

**Comment by qwertie** [comment]
Whew! The bug fix was straightforward (check git for history), but my `safePublish` script gave me some hassle (it turns out that it pays to specify package version numbers in the `"install"` list).

Version 1.6.0 is published.

**Comment by taylorsw04** [comment]
Wow, great catch! Thanks for that. Looking forward to updating :)

**Pull request merged**
